# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\LocalizationSystemGUI\mainWindow.ui'
#
# Created: Wed Mar  4 10:53:49 2015
# by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1440, 900)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = LocationPlot(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setObjectName(_fromUtf8("menuApplication"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuAbout_2 = QtGui.QMenu(self.menubar)
        self.menuAbout_2.setObjectName(_fromUtf8("menuAbout_2"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionDynamic_Tags = QtGui.QAction(mainWindow)
        self.actionDynamic_Tags.setObjectName(_fromUtf8("actionDynamic_Tags"))
        self.actionDangerous_Zones_Settings = QtGui.QAction(mainWindow)
        self.actionDangerous_Zones_Settings.setObjectName(_fromUtf8("actionDangerous_Zones_Settings"))
        self.actionAnchor_Settings = QtGui.QAction(mainWindow)
        self.actionAnchor_Settings.setObjectName(_fromUtf8("actionAnchor_Settings"))
        self.actionHistory_Query = QtGui.QAction(mainWindow)
        self.actionHistory_Query.setObjectName(_fromUtf8("actionHistory_Query"))
        self.actionHistory_Event = QtGui.QAction(mainWindow)
        self.actionHistory_Event.setObjectName(_fromUtf8("actionHistory_Event"))
        self.menuSettings.addAction(self.actionDynamic_Tags)
        self.menuSettings.addAction(self.actionDangerous_Zones_Settings)
        self.menuSettings.addAction(self.actionAnchor_Settings)
        self.menuAbout.addAction(self.actionHistory_Query)
        self.menuAbout.addAction(self.actionHistory_Event)
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuAbout_2.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Localization System", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("mainWindow", "4", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "TagID", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Location", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Time", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Event", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("mainWindow", "Tag 1", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("mainWindow", "(5,4,0)", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("mainWindow", "10:03 2015/3/4", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("mainWindow", "Warning: walking towards the danger zone 1.", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("mainWindow", "Tag 2", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("mainWindow", "(1,2,0)", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("mainWindow", "10:03 2015/3/4", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("mainWindow", "Normal", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("mainWindow", "Tag 3", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("mainWindow", "(3,3,0)", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("mainWindow", "10:03 2015/3/4", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("mainWindow", "Normal", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("mainWindow", "Tag 4", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("mainWindow", "(5,2,0)", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("mainWindow", "10:03 2015/3/4", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("mainWindow", "Normal", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuApplication.setTitle(_translate("mainWindow", "Application", None))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings", None))
        self.menuAbout.setTitle(_translate("mainWindow", "Query", None))
        self.menuAbout_2.setTitle(_translate("mainWindow", "About", None))
        self.actionDynamic_Tags.setText(_translate("mainWindow", "Dynamic Tag Settings", None))
        self.actionDangerous_Zones_Settings.setText(_translate("mainWindow", "Dangerous Zones Settings", None))
        self.actionAnchor_Settings.setText(_translate("mainWindow", "Anchor Settings", None))
        self.actionHistory_Query.setText(_translate("mainWindow", "History Trajectory", None))
        self.actionHistory_Event.setText(_translate("mainWindow", "History Event", None))

from locationplot import LocationPlot
